### ISSUE TITLE
invalid signature for non italian certificates

### ISSUE THREAD

**Issue by pdesterlich** [lucadentella/raspberry-dgc#7] opened 2021-09-26 20:20 UTC
Hi
i'm testing your code, it correctly validate italian issued certificates but it does not validate ("INVALID: signature") certificates issued from other nations (in my test, from Switzerland)
I understand that you get the certificate list from italian site, but i thought european signature database were linked together in order to validate foreign certificates too.
Do you have any clue on this?

**Comment by lucadentella** [comment] 2021-09-27 05:59
Hi Phelipe,

it's very strange: [this document](https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v2_en.pdf), says that each country should provide a "backend" for the certificates, aligned with the "master" European database. 

I asked some friends in France to test my app and they were able to validate their GPs. 
Could you test yours with the official italian app ("verificaC19")?
Which app are you using in Switzerland to test GPs? 

Thanks

**Comment by pdesterlich** [comment] 2021-09-27 06:17
Hi
I tested both certificates (italian and swiss) with both official apps for each country (Covid Check for Switzerland, VerificaC19 for italian) and they both are verified as valid.
I'll make some further test with your app later today

**Comment by lucadentella** [comment] 2021-09-27 06:20
Thanks! Let me know... I'm using the same URL of the official italian app to download the list of public keys so my app should give the same results.

**Comment by pdesterlich** [comment] 2021-09-27 07:45
I made some further tests, it seems the problem is some kind of error related to the algorithm used for signature that is unknow to the verifying server

i made some log calls in the try / catch block in the check DGC signature section

	try {
		const verifier = rs.KEYUTIL.getKey(certificate).getPublicKeyXYHex();
		signatureVerified = await dcc.checkSignature(verifier);
	} catch (e) {
		console.log("signature verify error")
		console.log(e)
	}

and this is what i get in the console

	signature verify error
	Error: Unknown algorithm, -37
		at E:\Progetti\test\raspberry-dgc-main\validatorServer\node_modules\cose-js\lib\sign.js:133:13
		at new Promise (<anonymous>)
		at doVerify (E:\Progetti\test\raspberry-dgc-main\validatorServer\node_modules\cose-js\lib\sign.js:131:10)
		at E:\Progetti\test\raspberry-dgc-main\validatorServer\node_modules\cose-js\lib\sign.js:251:16
		at runMicrotasks (<anonymous>)
		at processTicksAndRejections (internal/process/task_queues.js:95:5)
		at async Server.<anonymous> (E:\Progetti\test\raspberry-dgc-main\validatorServer\app.js:103:26)

if i bypass the signature verification (by ignoring the signatureVerified result) the process recognize the qr and correctly extract the informations (both for valid and expired qr)

**Comment by lucadentella** [comment] 2021-09-27 08:25
wierd, that errors comes from the cose-js library... 
please note that checkSignature() should fail if the current certificate is not the one used to sign the DGC... this is the reason why I cycle all the certificates looking for the only one valid for this specific DGC. Do you get the same errors for all the certificates?

**Comment by lucadentella** [comment] 2021-09-27 08:42
I tested with my GP and I actually get a different error when the signer certificate missmatch:

`Error: Signature missmatch
    at C:\Users\u82752\Documents\GitHub\raspberry-dgc\validatorServer\node_modules\cose-js\lib\sign.js:152:15
    at new Promise (<anonymous>)
    at doVerify (C:\Users\u82752\Documents\GitHub\raspberry-dgc\validatorServer\node_modules\cose-js\lib\sign.js:131:10)
    at C:\Users\u82752\Documents\GitHub\raspberry-dgc\validatorServer\node_modules\cose-js\lib\sign.js:251:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server.<anonymous> (C:\Users\u82752\Documents\GitHub\raspberry-dgc\validatorServer\app.js:103:26)`

**Comment by pdesterlich** [comment] 2021-09-27 08:47
yes, i get a full list of that same error
i didn't count the returned errors to check if it's the same number of certificates, i'll check that too.
i also tracked the origin of the error somewhere in the cosejs library (i first tried to upgrade dcc-utils to the latest version)

**Comment by lucadentella** [comment] 2021-09-27 08:51
I was able to reproduce the same error using the test data provided by Switzerland:
https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/CH

It fails for each certificate in the list with the same "Error: Unknown algorithm, -37"

If you do the same with test data from other countries (ES, FR...) it fails with the expected error "Error: Signature missmatch"

**Comment by lucadentella** [comment] 2021-09-27 09:15
I gave a look to the library source code, and it seems that it doesn't support the algorithm used in Switzerland:
https://github.com/erdtman/cose-js/blob/d86fb091553a1a9e6139545b3348f70de84097ff/lib/sign.js#L16

-37 is **PS256**
https://www.iana.org/assignments/cose/cose.xhtml#algorithms

The other DGCs I tested use **-7**

**Comment by lucadentella** [comment] 2021-09-27 09:19
A pull request: erdtman/cose-js#48 has been proposed to the cose-js library but not accepted yet. Unfortunately I cannot change COSE library because it is used by the dcc-utils library.

**Comment by pdesterlich** [comment] 2021-09-27 09:22
Yep, i also saw that pull request and was writing you about that.
It's not a priority for me right now, i'll check the cose-js repo to see if/when it will be implemented
Anyway thank you for your support

**Comment by lucadentella** [comment] 2021-09-27 09:27
You're welcome! May I ask - if you have time - to test the modified library (with PSS support) and verify if it solves?

**Comment by pdesterlich** [comment] 2021-09-27 11:37
While it's not a priority i will need that sometime in the future, so i'll check for the modified library and keep you updated.

**Comment by lucadentella** [comment] 2021-09-27 12:42
great! I also reported the issue to the dcc-utils library and they also requested the maintainer to accept the PR.
As soon as the library is updated in npm, it should also work with my project

**Comment by lucadentella** [comment] 2021-09-28 06:40
@pdesterlich the PR was merged some hours ago and the new version of the library (**0.7.0**) is already available with npm:
https://www.npmjs.com/package/cose-js

Could you try?
Thanks

**Comment by pdesterlich** [comment] 2021-09-28 06:57
I saw the merge on the cose-js repo, i'll check that later and let you know if it works

**Comment by pdesterlich** [comment] 2021-09-28 08:32
I tried updating to cose-js v0.7.0, still not working, different errors

for some signature i get this error

	Error: Invalid key data
		at Object.publicImport (E:\Progetti\test\raspberry-dgc-main\validatorServer\node_modules\dcc-utils\node_modules\node-rsa\src\formats\components.js:49:19)
		at Object.detectAndImport (E:\Progetti\test\raspberry-dgc-main\validatorServer\node_modules\dcc-utils\node_modules\node-rsa\src\formats\formats.js:66:48)
		at NodeRSA.module.exports.NodeRSA.importKey (E:\Progetti\test\raspberry-dgc-main\validatorServer\node_modules\dcc-utils\node_modules\node-rsa\src\NodeRSA.js:183:22)
		at doVerify (E:\Progetti\test\raspberry-dgc-main\validatorServer\node_modules\dcc-utils\node_modules\cose-js\lib\sign.js:176:31)
		at verifyInternal (E:\Progetti\test\raspberry-dgc-main\validatorServer\node_modules\dcc-utils\node_modules\cose-js\lib\sign.js:291:5)
		at E:\Progetti\test\raspberry-dgc-main\validatorServer\node_modules\dcc-utils\node_modules\cose-js\lib\sign.js:220:14
		at runMicrotasks (<anonymous>)
		at processTicksAndRejections (internal/process/task_queues.js:95:5)
		at async Server.<anonymous> (E:\Progetti\test\raspberry-dgc-main\validatorServer\app.js:104:26)

for other signatures i get this

	TypeError: rs.KEYUTIL.getKey(...).getPublicKeyXYHex is not a function
		at Server.<anonymous> (E:\Progetti\test\raspberry-dgc-main\validatorServer\app.js:103:54)
		at runMicrotasks (<anonymous>)
		at processTicksAndRejections (internal/process/task_queues.js:95:5)

i tried both my swiss certificate and test certificate, italian green pass still works fine

**Comment by lucadentella** [comment] 2021-09-28 08:38
`at NodeRSA.module.exports.NodeRSA.importKey (E:\Progetti\test\raspberry-dgc-main\validatorServer\node_modules\dcc-utils\node_modules\node-rsa\src\NodeRSA.js:183:22)`

NodeRSA is indeed the new library included to support the PS256 algo:

https://github.com/erdtman/cose-js/blob/004751a1bd88265cce768f3466ea86ecbf2945fa/lib/sign.js#L175-L176

I suspect some problems in the new code. I'll make some tests and report the issue to the maintaner
Thanks

**Comment by lucadentella** [comment] 2021-09-29 16:53
hi @pdesterlich 

I made some changes in the source code to correctly handle the format of the keys (ECDSA or RSA) the library expects.
I was able to validate some test DGCs provided by Switzerland, hopefully they used the same standard for "real" DGCs.
Can you test my code?

thanks

**Comment by pdesterlich** [comment] 2021-09-30 15:03
hi
i've been a little busy but i'll make some test tomorrow (if not later today)

**Comment by pdesterlich** [comment] 2021-09-30 22:57
i can confirm it correctly check green pass from switzerland with your changes and with the latest cose-js

**Comment by lucadentella** [comment] 2021-10-01 06:13
Thanks!!

**Closed by lucadentella** 2021-10-01 06:13 UTC
Labels: bug
